#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Generator

#include "Basic.hpp"

#include "ABP_Generator_classes.hpp"
#include "ABP_Generator_parameters.hpp"


namespace SDK
{

// Function ABP_Generator.ABP_Generator_C.ExecuteUbergraph_ABP_Generator
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Generator_C::ExecuteUbergraph_ABP_Generator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Generator_C", "ExecuteUbergraph_ABP_Generator");

	Params::ABP_Generator_C_ExecuteUbergraph_ABP_Generator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Generator.ABP_Generator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Generator_AnimGraphNode_SequenceEvaluator_2DD504D04D3C106DCBE8F2AABB3EE19A
// (BlueprintEvent)

void UABP_Generator_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Generator_AnimGraphNode_SequenceEvaluator_2DD504D04D3C106DCBE8F2AABB3EE19A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Generator_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Generator_AnimGraphNode_SequenceEvaluator_2DD504D04D3C106DCBE8F2AABB3EE19A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Generator.ABP_Generator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Generator_AnimGraphNode_ModifyBone_2987C6BF4EF9F5B6D208E192A792E914
// (BlueprintEvent)

void UABP_Generator_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Generator_AnimGraphNode_ModifyBone_2987C6BF4EF9F5B6D208E192A792E914()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Generator_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Generator_AnimGraphNode_ModifyBone_2987C6BF4EF9F5B6D208E192A792E914");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Generator.ABP_Generator_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Generator_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Generator_C", "AnimGraph");

	Params::ABP_Generator_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

