#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AFE_Regenerating

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AFE_Regenerating.AFE_Regenerating_C
// 0x0000 (0x0048 - 0x0048)
class UAFE_Regenerating_C final : public UAttachedParticlesAfflictionEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AFE_Regenerating_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AFE_Regenerating_C")
	}
	static class UAFE_Regenerating_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAFE_Regenerating_C>();
	}
};
DUMPER7_ASSERTS_UAFE_Regenerating_C;

}

