#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AFE_FP_MagicHoleMovement

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AFE_FP_MagicHoleMovement.AFE_FP_MagicHoleMovement_C
// 0x0000 (0x0048 - 0x0048)
class UAFE_FP_MagicHoleMovement_C final : public UAttachedParticlesAfflictionEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AFE_FP_MagicHoleMovement_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AFE_FP_MagicHoleMovement_C")
	}
	static class UAFE_FP_MagicHoleMovement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAFE_FP_MagicHoleMovement_C>();
	}
};
DUMPER7_ASSERTS_UAFE_FP_MagicHoleMovement_C;

}

