#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AFE_PowerAttack

#include "Basic.hpp"

#include "FSD_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass AFE_PowerAttack.AFE_PowerAttack_C
// 0x0008 (0x0030 - 0x0028)
class UAFE_PowerAttack_C final : public UAfflictionEffect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0028(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_AFE_PowerAttack(int32 EntryPoint);
	void ReceiveEndEffect(class UPawnAfflictionComponent* Target);
	void ReceiveBeginEffect(class UPawnAfflictionComponent* Target);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AFE_PowerAttack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AFE_PowerAttack_C")
	}
	static class UAFE_PowerAttack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAFE_PowerAttack_C>();
	}
};
DUMPER7_ASSERTS_UAFE_PowerAttack_C;

}

