#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AFE_TP_ShieldLink

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AFE_TP_ShieldLink.AFE_TP_ShieldLink_C
// 0x0000 (0x0028 - 0x0028)
class UAFE_TP_ShieldLink_C final : public UShieldLinkedAfflictionEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AFE_TP_ShieldLink_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AFE_TP_ShieldLink_C")
	}
	static class UAFE_TP_ShieldLink_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAFE_TP_ShieldLink_C>();
	}
};
DUMPER7_ASSERTS_UAFE_TP_ShieldLink_C;

}

