#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AFL_Infected_Player

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AFL_Infected_Player.AFL_Infected_Player_C
// 0x0000 (0x0060 - 0x0060)
class UAFL_Infected_Player_C final : public UScalingMeshAfflictionEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AFL_Infected_Player_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AFL_Infected_Player_C")
	}
	static class UAFL_Infected_Player_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAFL_Infected_Player_C>();
	}
};
DUMPER7_ASSERTS_UAFL_Infected_Player_C;

}

