#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Basic_Menu_ColorBarVertical

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ENUM_PixelWidths_structs.hpp"
#include "ENUM_MenuColors_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Basic_Menu_ColorBarVertical.Basic_Menu_ColorBarVertical_C
// 0x0020 (0x0280 - 0x0260)
class UBasic_Menu_ColorBarVertical_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                ColorBar;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               ColorBar_Sizer;                                    // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	ENUM_PixelWidths                              Thickness;                                         // 0x0278(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ENUM_MenuColors                               Color;                                             // 0x0279(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Basic_Menu_ColorBarVertical(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Basic_Menu_ColorBarVertical_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Basic_Menu_ColorBarVertical_C")
	}
	static class UBasic_Menu_ColorBarVertical_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBasic_Menu_ColorBarVertical_C>();
	}
};
DUMPER7_ASSERTS_UBasic_Menu_ColorBarVertical_C;

}

