#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Biome_ToolTip

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Biome_ToolTip.Biome_ToolTip_C
// 0x0050 (0x02B0 - 0x0260)
class UBiome_ToolTip_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Intro;                                             // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBasic_Menu_MinimalWindow_C*            Basic_Menu_MinimalWindow;                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_ResourceIcon_C*                  Basic_ResourceIconA;                               // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_ResourceIcon_C*                  Basic_ResourceIconB;                               // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFSDLabelWidget*                        ResourceAName;                                     // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFSDLabelWidget*                        ResourceBName;                                     // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FVector2D                              Position;                                          // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Alignment;                                         // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                Owner;                                             // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Biome_ToolTip(int32 EntryPoint);
	void Set_Tool_Tip_Owner(class UWidget* Owner_0);
	void PreConstruct(bool IsDesignTime);
	void SetTarget(class UWidget* Target_Widget);
	void SetPostionAndAlignment(const struct FVector2D& InPosition, const struct FVector2D& InAlignment);
	void SetData(class UResourceData* ResourceA, class UResourceData* ResourceB);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Biome_ToolTip_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Biome_ToolTip_C")
	}
	static class UBiome_ToolTip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBiome_ToolTip_C>();
	}
};
DUMPER7_ASSERTS_UBiome_ToolTip_C;

}

