#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AttachedState

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AttachedState.BP_AttachedState_C
// 0x0000 (0x0130 - 0x0130)
class UBP_AttachedState_C final : public UAttachedStateComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AttachedState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AttachedState_C")
	}
	static class UBP_AttachedState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AttachedState_C>();
	}
};
DUMPER7_ASSERTS_UBP_AttachedState_C;

}

