#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Chimney_Geyser_Carved_Base

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_Chimney_Geyser_Carved_Base.BP_Chimney_Geyser_Carved_Base_C.ExecuteUbergraph_BP_Chimney_Geyser_Carved_Base
// 0x0030 (0x0030 - 0x0000)
struct BP_Chimney_Geyser_Carved_Base_C_ExecuteUbergraph_BP_Chimney_Geyser_Carved_Base final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0008(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        K2Node_ComponentBoundEvent_point_1;                // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAtLocation_ReturnValue;         // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        K2Node_ComponentBoundEvent_point;                  // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Chimney_Geyser_Carved_Base_C_ExecuteUbergraph_BP_Chimney_Geyser_Carved_Base;

// Function BP_Chimney_Geyser_Carved_Base.BP_Chimney_Geyser_Carved_Base_C.BndEvt__TerrainDetect1_K2Node_ComponentBoundEvent_1_PointRemovedEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BP_Chimney_Geyser_Carved_Base_C_BndEvt__TerrainDetect1_K2Node_ComponentBoundEvent_1_PointRemovedEvent__DelegateSignature final
{
public:
	class USceneComponent*                        Point;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Chimney_Geyser_Carved_Base_C_BndEvt__TerrainDetect1_K2Node_ComponentBoundEvent_1_PointRemovedEvent__DelegateSignature;

// Function BP_Chimney_Geyser_Carved_Base.BP_Chimney_Geyser_Carved_Base_C.BndEvt__TerrainDetect_K2Node_ComponentBoundEvent_0_PointRemovedEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BP_Chimney_Geyser_Carved_Base_C_BndEvt__TerrainDetect_K2Node_ComponentBoundEvent_0_PointRemovedEvent__DelegateSignature final
{
public:
	class USceneComponent*                        Point;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Chimney_Geyser_Carved_Base_C_BndEvt__TerrainDetect_K2Node_ComponentBoundEvent_0_PointRemovedEvent__DelegateSignature;

// Function BP_Chimney_Geyser_Carved_Base.BP_Chimney_Geyser_Carved_Base_C.OnRep_IsBroken
// 0x0001 (0x0001 - 0x0000)
struct BP_Chimney_Geyser_Carved_Base_C_OnRep_IsBroken final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_Chimney_Geyser_Carved_Base_C_OnRep_IsBroken;

}

