#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DrinksBox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DrinksBox.BP_DrinksBox_C
// 0x0068 (0x0288 - 0x0220)
class ABP_DrinksBox_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        BartenderLocation;                                 // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	uint8                                         State;                                             // 0x0240(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_241[0x7];                                      // 0x0241(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class ABP_DrinksBox_C* DrinkBox)> OnAvailableForNewDrink;          // 0x0248(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class ABP_DrinksBox_C* DrinkBox)> OnDrinkReady;                    // 0x0258(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class ADrinkableActor*                        DrinkableActor;                                    // 0x0268(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(uint8 State)>   OnStateChanged;                                    // 0x0270(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         BarSlotIndex;                                      // 0x0280(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DrinksBox(int32 EntryPoint);
	void Fill_DrinkableActor();
	void OnDrinkableDestroyed(class AActor* DestroyedActor);
	void Spawn_Drink(class UDrinkableDataAsset* Drinkable);
	void OnLoaded_C20044584A6E4C14650B318543524FEE(TSubclassOf<class UObject> Loaded);
	void OnRep_State();
	void IsAvailable(bool* IsAvailable_0);
	void OnRep_DrinkableActor();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DrinksBox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DrinksBox_C")
	}
	static class ABP_DrinksBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DrinksBox_C>();
	}
};
DUMPER7_ASSERTS_ABP_DrinksBox_C;

}

