#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExplosiveEnemiesDamageLarge

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ExplosiveEnemiesDamageLarge.BP_ExplosiveEnemiesDamageLarge_C
// 0x0000 (0x01D8 - 0x01D8)
class UBP_ExplosiveEnemiesDamageLarge_C final : public UDamageComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ExplosiveEnemiesDamageLarge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ExplosiveEnemiesDamageLarge_C")
	}
	static class UBP_ExplosiveEnemiesDamageLarge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ExplosiveEnemiesDamageLarge_C>();
	}
};
DUMPER7_ASSERTS_UBP_ExplosiveEnemiesDamageLarge_C;

}

