#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ForgeScreen

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ForgeScreen.BP_ForgeScreen_C
// 0x0010 (0x0230 - 0x0220)
class ABP_ForgeScreen_C final : public AActor
{
public:
	class UWidgetComponent*                       Widget;                                            // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ForgeScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ForgeScreen_C")
	}
	static class ABP_ForgeScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ForgeScreen_C>();
	}
};
DUMPER7_ASSERTS_ABP_ForgeScreen_C;

}

