#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FSDCameraManager

#include "Basic.hpp"

#include "FSD_structs.hpp"
#include "FSD_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FSDCameraManager.BP_FSDCameraManager_C
// 0x0050 (0x2870 - 0x2820)
class ABP_FSDCameraManager_C final : public AFSDPlayerCameraManager
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2820(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   PhysicalSphere;                                    // 0x2828(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          SessionStarted;                                    // 0x2830(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2831[0x3];                                     // 0x2831(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxDistance;                                       // 0x2834(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              HideHUDForPhotography;                             // 0x2838(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              ShowHUDForPhotography;                             // 0x2848(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          UserVisibility;                                    // 0x2858(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	ECharacterCameraMode                          PreviousCameraMode;                                // 0x2859(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PauseGame;                                         // 0x285A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_285B[0x1];                                     // 0x285B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SphereReturnVelocity;                              // 0x285C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxDistanceTolerance;                              // 0x2860(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          KeyDebug;                                          // 0x2864(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2865[0x3];                                     // 0x2865(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxSpeed;                                          // 0x2868(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_FSDCameraManager(int32 EntryPoint);
	void LoaderStop();
	void LoaderStart(class ULevelSequence* LoaderLevelSequence);
	void Return_Camera();
	void TogglePhotographyMode(bool Active);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void OnPhotographySessionStart();
	void OnPhotographySessionEnd();
	void ReceiveDestroyed();
	void PhotographyCameraModify(const struct FVector& NewCameraLocation, const struct FVector& PreviousCameraLocation, const struct FVector& OriginalCameraLocation, struct FVector* ResultCameraLocation);
	void ReturnCameraMode(class APlayerCharacter* Target, ECharacterCameraMode NewCameraMode);
	void SetToThirdPersonCamera(struct FVector* New_Camera_Position);
	void SphereDirectionToPlayer(struct FVector* Direction);
	float SmoothReturnVelocity(const struct FVector& New_Camera_Location);
	void ChangeSpeed(float MaxSpeed_0);
	void ChangeMaxDistance(float MaxDistance_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FSDCameraManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FSDCameraManager_C")
	}
	static class ABP_FSDCameraManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FSDCameraManager_C>();
	}
};
DUMPER7_ASSERTS_ABP_FSDCameraManager_C;

}

