#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FoamRocket

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BoscoAbillityProjectile_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FoamRocket.BP_FoamRocket_C
// 0x0010 (0x0388 - 0x0378)
class ABP_FoamRocket_C final : public ABP_BoscoAbillityProjectile_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_FoamRocket_C;                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         GlobCount;                                         // 0x0380(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         spawned;                                           // 0x0384(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_FoamRocket(int32 EntryPoint);
	void OnImpacted(bool PredictedImpact, const struct FHitResult& HitResult);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FoamRocket_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FoamRocket_C")
	}
	static class ABP_FoamRocket_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FoamRocket_C>();
	}
};
DUMPER7_ASSERTS_ABP_FoamRocket_C;

}

