#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameMode

#include "Basic.hpp"

#include "FSD_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GameMode.BP_GameMode_C
// 0x0030 (0x0530 - 0x0500)
class ABP_GameMode_C : public AFSDGameMode
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0500(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UEnemyWaveManager*                      EnemyWaveManager;                                  // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UEncounterManager*                      EncounterManager;                                  // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           TimerHandle;                                       // 0x0520(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          CanSpawnBosco;                                     // 0x0528(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void GetEditorCharacterClass(class UPlayerCharacterID** Character_Class);
	void PreloadMuleClass();
	void TryPreloadCheatMenu();
	void GetEscapepodLocation(struct FTransform* Location);
	void EnableMuleButton();
	void DestroyNetworkedActors();
	void LoadToMission(class UMissionTemplate* mission);
	class UClass* GetDefaultPawnClassForController(class AController* InController);
	class AActor* ChoosePlayerStart(class AController* Player);
	void RecieveEndLevel();
	void ReceiveBeginPlay();
	void WaitForGeneration();
	void Recieve_ContinueTimerEnded();
	void Call_DropPod();
	void Trigger_End_Wave(bool cancelAllWaves);
	void SpawnBosco(const struct FTransform& Location);
	void RemoveBosco();
	void Handle_Bosco_Respawn();
	void OnPlayerLeave(class AFSDPlayerState* PlayerState);
	void Loaded();
	void DonkeyButtonPressed();
	void LoadSpaceRig();
	void ExecuteUbergraph_BP_GameMode(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameMode_C")
	}
	static class ABP_GameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GameMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_GameMode_C;

}

