#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HandheldTablet_UseProgress

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_HandheldTablet_UseProgress.BP_HandheldTablet_UseProgress_C.UserConstructionScript
// 0x0008 (0x0008 - 0x0000)
struct BP_HandheldTablet_UseProgress_C_UserConstructionScript final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_HandheldTablet_UseProgress_C_UserConstructionScript;

// Function BP_HandheldTablet_UseProgress.BP_HandheldTablet_UseProgress_C.SetBackgroundColor
// 0x0014 (0x0014 - 0x0000)
struct BP_HandheldTablet_UseProgress_C_SetBackgroundColor final
{
public:
	struct FLinearColor                           Value;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_HandheldTablet_UseProgress_C_SetBackgroundColor;

// Function BP_HandheldTablet_UseProgress.BP_HandheldTablet_UseProgress_C.OnSpawnRelease_Released
// 0x0001 (0x0001 - 0x0000)
struct BP_HandheldTablet_UseProgress_C_OnSpawnRelease_Released final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_HandheldTablet_UseProgress_C_OnSpawnRelease_Released;

// Function BP_HandheldTablet_UseProgress.BP_HandheldTablet_UseProgress_C.OnSpawnRelease_Attached
// 0x0010 (0x0010 - 0x0000)
struct BP_HandheldTablet_UseProgress_C_OnSpawnRelease_Attached final
{
public:
	class AActor*                                 Parent;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_HandheldTablet_UseProgress_C_OnSpawnRelease_Attached;

}

