#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IconGenerationManager

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IconGenerationManager.BP_IconGenerationManager_C
// 0x0000 (0x01E0 - 0x01E0)
class UBP_IconGenerationManager_C final : public UIconGenerationManager
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_IconGenerationManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_IconGenerationManager_C")
	}
	static class UBP_IconGenerationManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_IconGenerationManager_C>();
	}
};
DUMPER7_ASSERTS_UBP_IconGenerationManager_C;

}

