#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NetworkPlayGameMode

#include "Basic.hpp"

#include "BP_NetworkPlayGameMode_classes.hpp"
#include "BP_NetworkPlayGameMode_parameters.hpp"


namespace SDK
{

// Function BP_NetworkPlayGameMode.BP_NetworkPlayGameMode_C.GetDefaultPawnClassForController
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AController*                      InController                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UClass*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UClass* ABP_NetworkPlayGameMode_C::GetDefaultPawnClassForController(class AController* InController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NetworkPlayGameMode_C", "GetDefaultPawnClassForController");

	Params::BP_NetworkPlayGameMode_C_GetDefaultPawnClassForController Parms{};

	Parms.InController = InController;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_NetworkPlayGameMode.BP_NetworkPlayGameMode_C.RecieveAllDwarvesDown
// (Event, Public, BlueprintEvent)

void ABP_NetworkPlayGameMode_C::RecieveAllDwarvesDown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NetworkPlayGameMode_C", "RecieveAllDwarvesDown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NetworkPlayGameMode.BP_NetworkPlayGameMode_C.ExecuteUbergraph_BP_NetworkPlayGameMode
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NetworkPlayGameMode_C::ExecuteUbergraph_BP_NetworkPlayGameMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NetworkPlayGameMode_C", "ExecuteUbergraph_BP_NetworkPlayGameMode");

	Params::BP_NetworkPlayGameMode_C_ExecuteUbergraph_BP_NetworkPlayGameMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

