#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NetworkPlayGameMode

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_GameMode_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NetworkPlayGameMode.BP_NetworkPlayGameMode_C
// 0x0008 (0x0538 - 0x0530)
class ABP_NetworkPlayGameMode_C : public ABP_GameMode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_NetworkPlayGameMode_C;           // 0x0530(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	class UClass* GetDefaultPawnClassForController(class AController* InController);
	void RecieveAllDwarvesDown();
	void ExecuteUbergraph_BP_NetworkPlayGameMode(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NetworkPlayGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NetworkPlayGameMode_C")
	}
	static class ABP_NetworkPlayGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NetworkPlayGameMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_NetworkPlayGameMode_C;

}

