#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerState_Tutorial

#include "Basic.hpp"

#include "BP_PlayerState_Tutorial_classes.hpp"
#include "BP_PlayerState_Tutorial_parameters.hpp"


namespace SDK
{

// Function BP_PlayerState_Tutorial.BP_PlayerState_Tutorial_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PlayerState_Tutorial_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerState_Tutorial_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

