#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerState

#include "Basic.hpp"

#include "FSD_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerState.BP_PlayerState_C
// 0x0038 (0x04F0 - 0x04B8)
class ABP_PlayerState_C : public AFSDPlayerState
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPlayerResourceComponent*               PlayerResource;                                    // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          LateJoinFinished;                                  // 0x04D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          TestDropThing;                                     // 0x04D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4D2[0x6];                                      // 0x04D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 PodSpawnClass;                                     // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 PodBeacnClass;                                     // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          TestLateJoin;                                      // 0x04E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_PlayerState(int32 EntryPoint);
	void RespawnPlayer();
	void TestLatjoin();
	void CharacterSelected();
	void LogState();
	void ReceiveBeginPlay();
	void OnLateJoinFinished();
	void OnLoaded_97A4F0694E71C770F24EA6A654B14857(TSubclassOf<class UObject> Loaded);
	void OnLoaded_E2B28351414D5B2A20966496F0955946(TSubclassOf<class UObject> Loaded);
	void SpawnPlayerDirectly(class AController* Player);
	void SpawnPlayerInPod(class AFSDPlayerController* Player);
	void GetRessuplySpawnClass(class UClass** PodSpawnClass_0);
	void GetRessupyBeaconClass(class UClass** PodSpawnClass_0);
	TArray<struct FCreditsReward> GetDeepDiveCreditsReward(int32 StagesCompleted, int32 goldCollected);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerState_C")
	}
	static class ABP_PlayerState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerState_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlayerState_C;

}

