#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SphereTrigger

#include "Basic.hpp"

#include "BP_TriggerBase_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SphereTrigger.BP_SphereTrigger_C
// 0x0010 (0x0248 - 0x0238)
class ABP_SphereTrigger_C final : public ABP_TriggerBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_SphereTrigger_C;                 // 0x0238(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USphereComponent*                       Sphere;                                            // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void ExecuteUbergraph_BP_SphereTrigger(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SphereTrigger_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SphereTrigger_C")
	}
	static class ABP_SphereTrigger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SphereTrigger_C>();
	}
};
DUMPER7_ASSERTS_ABP_SphereTrigger_C;

}

