#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TunnelBlocker

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TunnelBlocker.BP_TunnelBlocker_C
// 0x0010 (0x0230 - 0x0220)
class ABP_TunnelBlocker_C final : public AActor
{
public:
	class UPathfinderCollisionComponent*          PathfinderCollision;                               // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TunnelBlocker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TunnelBlocker_C")
	}
	static class ABP_TunnelBlocker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TunnelBlocker_C>();
	}
};
DUMPER7_ASSERTS_ABP_TunnelBlocker_C;

}

