#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TutorialHeadline

#include "Basic.hpp"

#include "BP_TutorialHeadline_classes.hpp"
#include "BP_TutorialHeadline_parameters.hpp"


namespace SDK
{

// Function BP_TutorialHeadline.BP_TutorialHeadline_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TutorialHeadline_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TutorialHeadline_C", "ReceiveActorBeginOverlap");

	Params::BP_TutorialHeadline_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TutorialHeadline.BP_TutorialHeadline_C.ExecuteUbergraph_BP_TutorialHeadline
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TutorialHeadline_C::ExecuteUbergraph_BP_TutorialHeadline(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TutorialHeadline_C", "ExecuteUbergraph_BP_TutorialHeadline");

	Params::BP_TutorialHeadline_C_ExecuteUbergraph_BP_TutorialHeadline Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

