#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShakeDrilling

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShakeDrilling.CameraShakeDrilling_C
// 0x0000 (0x01B0 - 0x01B0)
class UCameraShakeDrilling_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShakeDrilling_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShakeDrilling_C")
	}
	static class UCameraShakeDrilling_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShakeDrilling_C>();
	}
};
DUMPER7_ASSERTS_UCameraShakeDrilling_C;

}

