#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShakeSpawnJoinDrilling

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShakeSpawnJoinDrilling.CameraShakeSpawnJoinDrilling_C
// 0x0000 (0x01B0 - 0x01B0)
class UCameraShakeSpawnJoinDrilling_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShakeSpawnJoinDrilling_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShakeSpawnJoinDrilling_C")
	}
	static class UCameraShakeSpawnJoinDrilling_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShakeSpawnJoinDrilling_C>();
	}
};
DUMPER7_ASSERTS_UCameraShakeSpawnJoinDrilling_C;

}

