#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_Generic_Explosions

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_Generic_Explosions.CameraShake_Generic_Explosions_C
// 0x0000 (0x01B0 - 0x01B0)
class UCameraShake_Generic_Explosions_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShake_Generic_Explosions_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShake_Generic_Explosions_C")
	}
	static class UCameraShake_Generic_Explosions_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_Generic_Explosions_C>();
	}
};
DUMPER7_ASSERTS_UCameraShake_Generic_Explosions_C;

}

