#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DE_LeafLoverDisableAllEffects

#include "Basic.hpp"

#include "DE_LeafLoverDisableAllEffects_classes.hpp"
#include "DE_LeafLoverDisableAllEffects_parameters.hpp"


namespace SDK
{

// Function DE_LeafLoverDisableAllEffects.DE_LeafLoverDisableAllEffects_C.ExecuteUbergraph_DE_LeafLoverDisableAllEffects
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDE_LeafLoverDisableAllEffects_C::ExecuteUbergraph_DE_LeafLoverDisableAllEffects(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DE_LeafLoverDisableAllEffects_C", "ExecuteUbergraph_DE_LeafLoverDisableAllEffects");

	Params::DE_LeafLoverDisableAllEffects_C_ExecuteUbergraph_DE_LeafLoverDisableAllEffects Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DE_LeafLoverDisableAllEffects.DE_LeafLoverDisableAllEffects_C.OnStartEffect
// (Event, Protected, BlueprintEvent)
// Parameters:
// class APlayerCharacter*                 Character_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDE_LeafLoverDisableAllEffects_C::OnStartEffect(class APlayerCharacter* Character_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DE_LeafLoverDisableAllEffects_C", "OnStartEffect");

	Params::DE_LeafLoverDisableAllEffects_C_OnStartEffect Parms{};

	Parms.Character_0 = Character_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

