#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DNA_Star_Medium

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DNA_Star_Medium.DNA_Star_Medium_C
// 0x0000 (0x0050 - 0x0050)
class UDNA_Star_Medium_C final : public UMissionDNA
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DNA_Star_Medium_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DNA_Star_Medium_C")
	}
	static class UDNA_Star_Medium_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDNA_Star_Medium_C>();
	}
};
DUMPER7_ASSERTS_UDNA_Star_Medium_C;

}

