#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_ActivatablePerks

#include "Basic.hpp"

#include "FSD_structs.hpp"
#include "FSD_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HUD_ActivatablePerks.HUD_ActivatablePerks_C
// 0x0018 (0x0298 - 0x0280)
class UHUD_ActivatablePerks_C final : public UFSDUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         WidgetBox;                                         // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EPerkHUDActivationLocation                    Location;                                          // 0x0290(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_HUD_ActivatablePerks(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void SetPerks(TArray<class UPerkAsset*>& Array);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HUD_ActivatablePerks_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HUD_ActivatablePerks_C")
	}
	static class UHUD_ActivatablePerks_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUD_ActivatablePerks_C>();
	}
};
DUMPER7_ASSERTS_UHUD_ActivatablePerks_C;

}

