#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_TopBar_ResourceCounter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "ENUM_MenuColors_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ITM_TopBar_ResourceCounter.ITM_TopBar_ResourceCounter_C
// 0x0048 (0x02A8 - 0x0260)
class UITM_TopBar_ResourceCounter_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBasic_AnimatedNumber_C*                Number;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_ResourceIcon_C*                  ResourceLeft;                                      // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_ResourceIcon_C*                  ResourceRight;                                     // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UResourceData*                          Resource;                                          // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         amount;                                            // 0x0288(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         RequiredAmount;                                    // 0x028C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IconOnRight;                                       // 0x0290(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          HideWhenZero;                                      // 0x0291(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_292[0x6];                                      // 0x0292(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBasic_ToolTip_C*                       ToolTip;                                           // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DoCountAnim;                                       // 0x02A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_ITM_TopBar_ResourceCounter(int32 EntryPoint);
	void UpdateResourceBehavior(bool HideWhenZero_0, bool DoCountAnim_0);
	void UpdateFromSave();
	void OnResourceAmountChanged_Event(class UResourceData* Resource_0, float currentAmount);
	void Construct();
	void UpdateAmount(float InAmount);
	void PreConstruct(bool IsDesignTime);
	void SetResourceData(class UResourceData* InResource, float InAmount, float InRequiredAmount);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ITM_TopBar_ResourceCounter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ITM_TopBar_ResourceCounter_C")
	}
	static class UITM_TopBar_ResourceCounter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UITM_TopBar_ResourceCounter_C>();
	}
};
DUMPER7_ASSERTS_UITM_TopBar_ResourceCounter_C;

}

