#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_MenuDamageIndicator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ITM_MenuDamageIndicator.ITM_MenuDamageIndicator_C
// 0x0020 (0x0280 - 0x0260)
class UITM_MenuDamageIndicator_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       DamageTaken;                                       // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_Damage;                                      // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUserWidget*                            Menu;                                              // 0x0278(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ITM_MenuDamageIndicator(int32 EntryPoint);
	void SetMenu(class UUserWidget* EscapeMenu);
	void OnAnimFinished();
	void OnHit(float Damage, const struct FDamageData& DamageData, bool anyHealthLost);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ITM_MenuDamageIndicator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ITM_MenuDamageIndicator_C")
	}
	static class UITM_MenuDamageIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UITM_MenuDamageIndicator_C>();
	}
};
DUMPER7_ASSERTS_UITM_MenuDamageIndicator_C;

}

