#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LIB_PerkColors

#include "Basic.hpp"

#include "FSD_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LIB_PerkColors.LIB_PerkColors_C
// 0x0000 (0x0028 - 0x0028)
class ULIB_PerkColors_C final : public UBlueprintFunctionLibrary
{
public:
	static void PerkColorByState(EPerkUsageType InPerkType, EPerkTierState InPerkState, class UObject* __WorldContext, struct FLinearColor* OutBackground, struct FLinearColor* OutBorder, struct FLinearColor* OutIcon);
	static void PerkColorFromType(EPerkUsageType InType, class UObject* __WorldContext, struct FLinearColor* OutColor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LIB_PerkColors_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LIB_PerkColors_C")
	}
	static class ULIB_PerkColors_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULIB_PerkColors_C>();
	}
};
DUMPER7_ASSERTS_ULIB_PerkColors_C;

}

