#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LVL_NewTutorial

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LVL_NewTutorial.LVL_NewTutorial_C
// 0x0028 (0x0250 - 0x0228)
class ALVL_NewTutorial_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_TutorialTriggerManager_C*           Manager;                                           // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEWC_TutorialGrunts_C*                  WaveManager;                                       // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHUD_TutorialLevelManager_C*            WidgetManager;                                     // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFSDPlayerController*                   PlayerController;                                  // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void MessageReceived_Event_0(class FName TriggerName);
	void ReceiveBeginPlay();
	void objectivesCompleted();
	void ExecuteUbergraph_LVL_NewTutorial(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LVL_NewTutorial_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LVL_NewTutorial_C")
	}
	static class ALVL_NewTutorial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALVL_NewTutorial_C>();
	}
};
DUMPER7_ASSERTS_ALVL_NewTutorial_C;

}

