#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionControl_MainDialogue

#include "Basic.hpp"

#include "MissionControl_MainDialogue_classes.hpp"
#include "MissionControl_MainDialogue_parameters.hpp"


namespace SDK
{

// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.ExecuteUbergraph_MissionControl_MainDialogue
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionControl_MainDialogue_C::ExecuteUbergraph_MissionControl_MainDialogue(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "ExecuteUbergraph_MissionControl_MainDialogue");

	Params::MissionControl_MainDialogue_C_ExecuteUbergraph_MissionControl_MainDialogue Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.HideMissionShout
// (BlueprintCallable, BlueprintEvent)

void UMissionControl_MainDialogue_C::HideMissionShout()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "HideMissionShout");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.OnMissionShoutEnd
// (BlueprintCallable, BlueprintEvent)

void UMissionControl_MainDialogue_C::OnMissionShoutEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "OnMissionShoutEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMissionControl_MainDialogue_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "PreConstruct");

	Params::MissionControl_MainDialogue_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMissionControl_MainDialogue_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.OnMissionShout
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text_0                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// float                                   Duration_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionControl_MainDialogue_C::OnMissionShout(const class FText& Text_0, float Duration_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "OnMissionShout");

	Params::MissionControl_MainDialogue_C_OnMissionShout Parms{};

	Parms.Text_0 = std::move(Text_0);
	Parms.Duration_0 = Duration_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.Start Running Text
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// float                                   Duration_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionControl_MainDialogue_C::Start_Running_Text(const class FText& Text_0, float Duration_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "Start Running Text");

	Params::MissionControl_MainDialogue_C_Start_Running_Text Parms{};

	Parms.Text_0 = std::move(Text_0);
	Parms.Duration_0 = Duration_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.SpeakManually
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UDialogDataAsset*                 MissionShout                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  Duration_0                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAudioComponent**                 AudioComponent                                         (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionControl_MainDialogue_C::SpeakManually(class UDialogDataAsset* MissionShout, float* Duration_0, class UAudioComponent** AudioComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "SpeakManually");

	Params::MissionControl_MainDialogue_C_SpeakManually Parms{};

	Parms.MissionShout = MissionShout;

	UObject::ProcessEvent(Func, &Parms);

	if (Duration_0 != nullptr)
		*Duration_0 = Parms.Duration_0;

	if (AudioComponent != nullptr)
		*AudioComponent = Parms.AudioComponent;
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.SpeakEntryManually
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDialogStruct&             entry                                                  (BlueprintVisible, BlueprintReadOnly, Parm)
// float*                                  Duration_0                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAudioComponent**                 AudioComponent                                         (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionControl_MainDialogue_C::SpeakEntryManually(const struct FDialogStruct& entry, float* Duration_0, class UAudioComponent** AudioComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "SpeakEntryManually");

	Params::MissionControl_MainDialogue_C_SpeakEntryManually Parms{};

	Parms.entry = std::move(entry);

	UObject::ProcessEvent(Func, &Parms);

	if (Duration_0 != nullptr)
		*Duration_0 = Parms.Duration_0;

	if (AudioComponent != nullptr)
		*AudioComponent = Parms.AudioComponent;
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.StopRunningText
// (Public, BlueprintCallable, BlueprintEvent)

void UMissionControl_MainDialogue_C::StopRunningText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "StopRunningText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.TickRunningText
// (Private, BlueprintCallable, BlueprintEvent)

void UMissionControl_MainDialogue_C::TickRunningText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "TickRunningText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.SetProgress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Finished                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMissionControl_MainDialogue_C::SetProgress(float Progress, bool* Finished)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "SetProgress");

	Params::MissionControl_MainDialogue_C_SetProgress Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);

	if (Finished != nullptr)
		*Finished = Parms.Finished;
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.Reset
// (Public, BlueprintCallable, BlueprintEvent)

void UMissionControl_MainDialogue_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionControl_MainDialogue.MissionControl_MainDialogue_C.SetPreview
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UDialogDataAsset*                 PreviewShout_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionControl_MainDialogue_C::SetPreview(class UDialogDataAsset* PreviewShout_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionControl_MainDialogue_C", "SetPreview");

	Params::MissionControl_MainDialogue_C_SetPreview Parms{};

	Parms.PreviewShout_0 = PreviewShout_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

