#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModioTagWidget

#include "Basic.hpp"

#include "ModioUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ModioTagWidget.ModioTagWidget_C
// 0x0000 (0x02B8 - 0x02B8)
class UModioTagWidget_C final : public UModioTagWidgetBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ModioTagWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ModioTagWidget_C")
	}
	static class UModioTagWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UModioTagWidget_C>();
	}
};
DUMPER7_ASSERTS_UModioTagWidget_C;

}

