#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModioModBrowserWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ModioUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ModioModBrowserWidget.ModioModBrowserWidget_C
// 0x0020 (0x0380 - 0x0360)
class UModioModBrowserWidget_C final : public UModioMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UModioDownloadQueue_C*                  ModioDownloadQueue;                                // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UModioRefineSearchDrawer_C*             ModioRefineSearchDrawer;                           // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InfoScreen_C*                       UI_Info_Screen;                                    // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ModioModBrowserWidget(int32 EntryPoint);
	void Construct();
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ModioModBrowserWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ModioModBrowserWidget_C")
	}
	static class UModioModBrowserWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UModioModBrowserWidget_C>();
	}
};
DUMPER7_ASSERTS_UModioModBrowserWidget_C;

}

