#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OBJ_FindItems_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function OBJ_FindItems_Base.OBJ_FindItems_Base_C.GetObjectiveDescription
// 0x0090 (0x0090 - 0x0000)
struct OBJ_FindItems_Base_C_GetObjectiveDescription final
{
public:
	float                                         missionLength;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm)
	int32                                         CallFunc_GetObjectiveAmount_ReturnValue;           // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0028(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0068(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0078(0x0018)()
};
DUMPER7_ASSERTS_OBJ_FindItems_Base_C_GetObjectiveDescription;

// Function OBJ_FindItems_Base.OBJ_FindItems_Base_C.GetInMissionText
// 0x0018 (0x0018 - 0x0000)
struct OBJ_FindItems_Base_C_GetInMissionText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_OBJ_FindItems_Base_C_GetInMissionText;

// Function OBJ_FindItems_Base.OBJ_FindItems_Base_C.GetObjectiveAmount
// 0x0020 (0x0020 - 0x0000)
struct OBJ_FindItems_Base_C_GetObjectiveAmount final
{
public:
	float                                         missionLength;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OBJ_FindItems_Base_C_GetObjectiveAmount;

// Function OBJ_FindItems_Base.OBJ_FindItems_Base_C.GetObjectiveIcon
// 0x0008 (0x0008 - 0x0000)
struct OBJ_FindItems_Base_C_GetObjectiveIcon final
{
public:
	class UTexture2D*                             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OBJ_FindItems_Base_C_GetObjectiveIcon;

// Function OBJ_FindItems_Base.OBJ_FindItems_Base_C.GetInMissionCounterText
// 0x00C0 (0x00C0 - 0x0000)
struct OBJ_FindItems_Base_C_GetInMissionCounterText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0018(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0058(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0098(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00A8(0x0018)()
};
DUMPER7_ASSERTS_OBJ_FindItems_Base_C_GetInMissionCounterText;

// Function OBJ_FindItems_Base.OBJ_FindItems_Base_C.GetInMissionCounterIcon
// 0x0008 (0x0008 - 0x0000)
struct OBJ_FindItems_Base_C_GetInMissionCounterIcon final
{
public:
	class UTexture2D*                             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OBJ_FindItems_Base_C_GetInMissionCounterIcon;

// Function OBJ_FindItems_Base.OBJ_FindItems_Base_C.IsObjectiveResource
// 0x0010 (0x0010 - 0x0000)
struct OBJ_FindItems_Base_C_IsObjectiveResource final
{
public:
	class UResourceData*                          InResource;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_OBJ_FindItems_Base_C_IsObjectiveResource;

}

