#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OBJ_DD_Elimination_Eggs

#include "Basic.hpp"

#include "FSD_structs.hpp"


namespace SDK::Params
{

// Function OBJ_DD_Elimination_Eggs.OBJ_DD_Elimination_Eggs_C.GetObjectiveAmount
// 0x0008 (0x0008 - 0x0000)
struct OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount final
{
public:
	float                                         missionLength;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount;

// Function OBJ_DD_Elimination_Eggs.OBJ_DD_Elimination_Eggs_C.GetMissionIcon
// 0x0030 (0x0030 - 0x0000)
struct OBJ_DD_Elimination_Eggs_C_GetMissionIcon final
{
public:
	struct FObjectiveMissionIcon                  ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NoDestructor)
	struct FObjectiveMissionIcon                  CallFunc_GetPrimaryObjectiveIconFromAsset_ReturnValue; // 0x0018(0x0018)(NoDestructor)
};
DUMPER7_ASSERTS_OBJ_DD_Elimination_Eggs_C_GetMissionIcon;

}

