#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Options_ToggleTerrainScanner

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Options_ToggleTerrainScanner.Options_ToggleTerrainScanner_C
// 0x0010 (0x0270 - 0x0260)
class UOptions_ToggleTerrainScanner_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBasic_CheckBox_C*                      Basic_CheckBox;                                    // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Options_ToggleTerrainScanner(int32 EntryPoint);
	void ShowOptions();
	void UINeedsUpdate();
	void BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature(bool IsChecked);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Options_ToggleTerrainScanner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Options_ToggleTerrainScanner_C")
	}
	static class UOptions_ToggleTerrainScanner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOptions_ToggleTerrainScanner_C>();
	}
};
DUMPER7_ASSERTS_UOptions_ToggleTerrainScanner_C;

}

