#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PLS_NewTutorial

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PLS_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PLS_NewTutorial.PLS_NewTutorial_C
// 0x0008 (0x0500 - 0x04F8)
class APLS_NewTutorial_C final : public APLS_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PLS_NewTutorial_C;                  // 0x04F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void CreateCaveGraph();
	void ExecuteUbergraph_PLS_NewTutorial(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PLS_NewTutorial_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PLS_NewTutorial_C")
	}
	static class APLS_NewTutorial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APLS_NewTutorial_C>();
	}
};
DUMPER7_ASSERTS_APLS_NewTutorial_C;

}

