#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScreenOverlay_Afflictions

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ScreenOverlay_Afflictions.ScreenOverlay_Afflictions_C
// 0x0070 (0x02D0 - 0x0260)
class UScreenOverlay_Afflictions_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCanvasPanel*                           RootCanvas;                                        // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class APlayerCharacter*                       Player;                                            // 0x0270(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHealthComponent*                       HealthComponent;                                   // 0x0278(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<class UPlayerAfflictionOverlay*, class UPlayerAfflictionOverlayWidget*> ActiveOverlays;     // 0x0280(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void FindOverlayWidget(class UPlayerAfflictionOverlay* OverlayData, bool CreateIfNew, class UPlayerAfflictionOverlayWidget** OutWidget);
	void Construct();
	void OnShowOverlay_Event(class UPlayerAfflictionOverlay* Overlay);
	void OnHideOverlay_Event(class UPlayerAfflictionOverlay* Overlay);
	void ExecuteUbergraph_ScreenOverlay_Afflictions(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ScreenOverlay_Afflictions_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ScreenOverlay_Afflictions_C")
	}
	static class UScreenOverlay_Afflictions_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScreenOverlay_Afflictions_C>();
	}
};
DUMPER7_ASSERTS_UScreenOverlay_Afflictions_C;

}

