#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TSK_FindRandomPointFrom

#include "Basic.hpp"

#include "TSK_FindRandomPointFrom_classes.hpp"
#include "TSK_FindRandomPointFrom_parameters.hpp"


namespace SDK
{

// Function TSK_FindRandomPointFrom.TSK_FindRandomPointFrom_C.ExecuteUbergraph_TSK_FindRandomPointFrom
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTSK_FindRandomPointFrom_C::ExecuteUbergraph_TSK_FindRandomPointFrom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TSK_FindRandomPointFrom_C", "ExecuteUbergraph_TSK_FindRandomPointFrom");

	Params::TSK_FindRandomPointFrom_C_ExecuteUbergraph_TSK_FindRandomPointFrom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TSK_FindRandomPointFrom.TSK_FindRandomPointFrom_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTSK_FindRandomPointFrom_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TSK_FindRandomPointFrom_C", "ReceiveExecuteAI");

	Params::TSK_FindRandomPointFrom_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TSK_FindRandomPointFrom.TSK_FindRandomPointFrom_C.snap
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    SnapToCeiling_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UDeepPathfinderMovement*          Pathfinder                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector&                         Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTSK_FindRandomPointFrom_C::snap(bool SnapToCeiling_0, class UDeepPathfinderMovement* Pathfinder, struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TSK_FindRandomPointFrom_C", "snap");

	Params::TSK_FindRandomPointFrom_C_snap Parms{};

	Parms.SnapToCeiling_0 = SnapToCeiling_0;
	Parms.Pathfinder = Pathfinder;
	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);

	Location = std::move(Parms.Location);
}


// Function TSK_FindRandomPointFrom.TSK_FindRandomPointFrom_C.GetLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector UTSK_FindRandomPointFrom_C::GetLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TSK_FindRandomPointFrom_C", "GetLocation");

	Params::TSK_FindRandomPointFrom_C_GetLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function TSK_FindRandomPointFrom.TSK_FindRandomPointFrom_C.GetBestFlatGround
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Origin                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Array_Element                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTSK_FindRandomPointFrom_C::GetBestFlatGround(const struct FVector& Origin, struct FVector* Array_Element)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TSK_FindRandomPointFrom_C", "GetBestFlatGround");

	Params::TSK_FindRandomPointFrom_C_GetBestFlatGround Parms{};

	Parms.Origin = std::move(Origin);

	UObject::ProcessEvent(Func, &Parms);

	if (Array_Element != nullptr)
		*Array_Element = std::move(Parms.Array_Element);
}

}

