#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tutorial_Hint_FocusShot

#include "Basic.hpp"

#include "Tutorial_Hint_FocusShot_classes.hpp"
#include "Tutorial_Hint_FocusShot_parameters.hpp"


namespace SDK
{

// Function Tutorial_Hint_FocusShot.Tutorial_Hint_FocusShot_C.ExecuteUbergraph_Tutorial_Hint_FocusShot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTutorial_Hint_FocusShot_C::ExecuteUbergraph_Tutorial_Hint_FocusShot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_Hint_FocusShot_C", "ExecuteUbergraph_Tutorial_Hint_FocusShot");

	Params::Tutorial_Hint_FocusShot_C_ExecuteUbergraph_Tutorial_Hint_FocusShot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tutorial_Hint_FocusShot.Tutorial_Hint_FocusShot_C.FullyFocusedEvent_Event
// (BlueprintCallable, BlueprintEvent)

void UTutorial_Hint_FocusShot_C::FullyFocusedEvent_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_Hint_FocusShot_C", "FullyFocusedEvent_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tutorial_Hint_FocusShot.Tutorial_Hint_FocusShot_C.OnItemEquipped_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AItem*                            Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTutorial_Hint_FocusShot_C::OnItemEquipped_Event(class AItem* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_Hint_FocusShot_C", "OnItemEquipped_Event");

	Params::Tutorial_Hint_FocusShot_C_OnItemEquipped_Event Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tutorial_Hint_FocusShot.Tutorial_Hint_FocusShot_C.ReceiveOnInitialized
// (Event, Protected, BlueprintEvent)

void UTutorial_Hint_FocusShot_C::ReceiveOnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_Hint_FocusShot_C", "ReceiveOnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}

}

