#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco

#include "Basic.hpp"


namespace SDK::Params
{

// Function Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco.Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco_C.ExecuteUbergraph_Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco
// 0x0058 (0x0058 - 0x0000)
struct Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco_C_ExecuteUbergraph_Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AItem*                                  K2Node_CustomEvent_Item;                           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlagueSoaperItem*                      K2Node_DynamicCast_AsPlague_Soaper_Item;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class AItem* Item)>            K2Node_CreateDelegate_OutputDelegate;              // 0x001C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	const class UMissionWarning*                  Temp_object_Variable;                              // 0x0030(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFSDGameInstance*                       CallFunc_GetFSDGameInstance_ReturnValue;           // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFSDGameInstance*                       CallFunc_GetFSDGameInstance_ReturnValue_1;         // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco_C_ExecuteUbergraph_Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco;

// Function Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco.Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco_C.OnItemEquipped_LithoFoamer
// 0x0008 (0x0008 - 0x0000)
struct Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco_C_OnItemEquipped_LithoFoamer final
{
public:
	class AItem*                                  Item;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Tutorial_Hint_PlagueWarning_SporeTowerCleaning_Bosco_C_OnItemEquipped_LithoFoamer;

}

