#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tutorial_Hint_Flares

#include "Basic.hpp"

#include "Tutorial_Hint_Flares_classes.hpp"
#include "Tutorial_Hint_Flares_parameters.hpp"


namespace SDK
{

// Function Tutorial_Hint_Flares.Tutorial_Hint_Flares_C.ExecuteUbergraph_Tutorial_Hint_Flares
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTutorial_Hint_Flares_C::ExecuteUbergraph_Tutorial_Hint_Flares(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_Hint_Flares_C", "ExecuteUbergraph_Tutorial_Hint_Flares");

	Params::Tutorial_Hint_Flares_C_ExecuteUbergraph_Tutorial_Hint_Flares Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tutorial_Hint_Flares.Tutorial_Hint_Flares_C.ReceiveOnInitialized
// (Event, Protected, BlueprintEvent)

void UTutorial_Hint_Flares_C::ReceiveOnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_Hint_Flares_C", "ReceiveOnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tutorial_Hint_Flares.Tutorial_Hint_Flares_C.ReceiveOnHidden
// (Event, Protected, BlueprintEvent)

void UTutorial_Hint_Flares_C::ReceiveOnHidden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_Hint_Flares_C", "ReceiveOnHidden");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tutorial_Hint_Flares.Tutorial_Hint_Flares_C.OnFlareThrown
// (BlueprintCallable, BlueprintEvent)

void UTutorial_Hint_Flares_C::OnFlareThrown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_Hint_Flares_C", "OnFlareThrown");

	UObject::ProcessEvent(Func, nullptr);
}

}

