#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_BlackOverlay

#include "Basic.hpp"

#include "UI_BlackOverlay_classes.hpp"
#include "UI_BlackOverlay_parameters.hpp"


namespace SDK
{

// Function UI_BlackOverlay.UI_BlackOverlay_C.ExecuteUbergraph_UI_BlackOverlay
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BlackOverlay_C::ExecuteUbergraph_UI_BlackOverlay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BlackOverlay_C", "ExecuteUbergraph_UI_BlackOverlay");

	Params::UI_BlackOverlay_C_ExecuteUbergraph_UI_BlackOverlay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BlackOverlay.UI_BlackOverlay_C.SetFadeProgress
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   fade_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ToSpaceRig_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UTexture*                         LoadingImage_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BlackOverlay_C::SetFadeProgress(float fade_0, bool ToSpaceRig_0, class UTexture* LoadingImage_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BlackOverlay_C", "SetFadeProgress");

	Params::UI_BlackOverlay_C_SetFadeProgress Parms{};

	Parms.fade_0 = fade_0;
	Parms.ToSpaceRig_0 = ToSpaceRig_0;
	Parms.LoadingImage_0 = LoadingImage_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BlackOverlay.UI_BlackOverlay_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_BlackOverlay_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BlackOverlay_C", "PreConstruct");

	Params::UI_BlackOverlay_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BlackOverlay.UI_BlackOverlay_C.SetProgress
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InFade                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InToSpacerig                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UTexture*                         InLoadingImage                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BlackOverlay_C::SetProgress(float InFade, bool InToSpacerig, class UTexture* InLoadingImage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BlackOverlay_C", "SetProgress");

	Params::UI_BlackOverlay_C_SetProgress Parms{};

	Parms.InFade = InFade;
	Parms.InToSpacerig = InToSpacerig;
	Parms.InLoadingImage = InLoadingImage;

	UObject::ProcessEvent(Func, &Parms);
}

}

