#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Bar_SupporterLabel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Bar_SupporterLabel.UI_Bar_SupporterLabel_C
// 0x0028 (0x0288 - 0x0260)
class UUI_Bar_SupporterLabel_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         SupporterBox;                                      // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             SupporterHeader;                                   // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SupportIconLeft;                                   // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         Font_Size;                                         // 0x0280(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         Icon_Size;                                         // 0x0284(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_Bar_SupporterLabel(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetDrinkable(class UDrinkableDataAsset* Drinkable, bool* IsSpecialEdition, class UDrinkableDataAsset** OutDrinkable);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Bar_SupporterLabel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Bar_SupporterLabel_C")
	}
	static class UUI_Bar_SupporterLabel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Bar_SupporterLabel_C>();
	}
};
DUMPER7_ASSERTS_UUI_Bar_SupporterLabel_C;

}

