#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Bar_Inventory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Bar_Inventory.UI_Bar_Inventory_C
// 0x0020 (0x0280 - 0x0260)
class UUI_Bar_Inventory_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         InventoryBox;                                      // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UResourceData*>                  Resources;                                         // 0x0270(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_UI_Bar_Inventory(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Bar_Inventory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Bar_Inventory_C")
	}
	static class UUI_Bar_Inventory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Bar_Inventory_C>();
	}
};
DUMPER7_ASSERTS_UUI_Bar_Inventory_C;

}

