#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_FrozenInputDirectionIcon

#include "Basic.hpp"

#include "FSD_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_FrozenInputDirectionIcon.UI_FrozenInputDirectionIcon_C
// 0x00A8 (0x0308 - 0x0260)
class UUI_FrozenInputDirectionIcon_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       failed;                                            // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Pressed;                                           // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Active;                                            // 0x0278(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_92;                                          // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UTexture2D*>                     Textures;                                          // 0x0288(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FWidgetTransform                       EForward;                                          // 0x0298(0x001C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FWidgetTransform                       ERight;                                            // 0x02B4(0x001C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FWidgetTransform                       EBack;                                             // 0x02D0(0x001C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FWidgetTransform                       ELeft;                                             // 0x02EC(0x001C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void ExecuteUbergraph_UI_FrozenInputDirectionIcon(int32 EntryPoint);
	void OnFailed();
	void OnPressed();
	void SetActive(bool Active_0);
	void SetDirection(EThawInputDirection Direction);
	void Finished_CD1267A8441EB6B05873859D8163D918();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_FrozenInputDirectionIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_FrozenInputDirectionIcon_C")
	}
	static class UUI_FrozenInputDirectionIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_FrozenInputDirectionIcon_C>();
	}
};
DUMPER7_ASSERTS_UUI_FrozenInputDirectionIcon_C;

}

