#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_PatchNotes

#include "Basic.hpp"

#include "FSD_structs.hpp"


namespace SDK::Params
{

// Function UI_PatchNotes.UI_PatchNotes_C.ExecuteUbergraph_UI_PatchNotes
// 0x0050 (0x0050 - 0x0000)
struct UI_PatchNotes_C_ExecuteUbergraph_UI_PatchNotes final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Min_ReturnValue;                          // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FText>                           CallFunc_SelectByPlatform_ReturnValue;             // 0x0030(0x0010)(ReferenceParm)
	TArray<class FText>                           CallFunc_SelectByPlatform_ReturnValue_1;           // 0x0040(0x0010)(ReferenceParm)
};
DUMPER7_ASSERTS_UI_PatchNotes_C_ExecuteUbergraph_UI_PatchNotes;

// Function UI_PatchNotes.UI_PatchNotes_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_PatchNotes_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_PatchNotes_C_PreConstruct;

// Function UI_PatchNotes.UI_PatchNotes_C.UpdatePatchNotes
// 0x0030 (0x0030 - 0x0000)
struct UI_PatchNotes_C_UpdatePatchNotes final
{
public:
	class FText                                   CallFunc_Array_Get_Item;                           // 0x0000(0x0018)()
	class FText                                   CallFunc_Array_Get_Item_1;                         // 0x0018(0x0018)()
};
DUMPER7_ASSERTS_UI_PatchNotes_C_UpdatePatchNotes;

// Function UI_PatchNotes.UI_PatchNotes_C.SelectByPlatform
// 0x0058 (0x0058 - 0x0000)
struct UI_PatchNotes_C_SelectByPlatform final
{
public:
	TArray<class FText>                           Default;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<class FText>                           Xbox;                                              // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<class FText>                           Sony;                                              // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<class FText>                           ReturnValue;                                       // 0x0030(0x0010)(Parm, OutParm, ReturnParm)
	EFSDTargetPlatform                            Temp_byte_Variable;                                // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFSDTargetPlatform                            CallFunc_FSDTargetPlatform_ReturnValue;            // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FText>                           K2Node_Select_Default;                             // 0x0048(0x0010)(ReferenceParm)
};
DUMPER7_ASSERTS_UI_PatchNotes_C_SelectByPlatform;

}

