#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TutorialGrenade

#include "Basic.hpp"

#include "W_TutorialGrenade_classes.hpp"
#include "W_TutorialGrenade_parameters.hpp"


namespace SDK
{

// Function W_TutorialGrenade.W_TutorialGrenade_C.OnShown
// (Event, Public, BlueprintEvent)

void UW_TutorialGrenade_C::OnShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TutorialGrenade_C", "OnShown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TutorialGrenade.W_TutorialGrenade_C.UpdateTaskText
// (BlueprintCallable, BlueprintEvent)

void UW_TutorialGrenade_C::UpdateTaskText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TutorialGrenade_C", "UpdateTaskText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TutorialGrenade.W_TutorialGrenade_C.GrenadeThrown
// (BlueprintCallable, BlueprintEvent)

void UW_TutorialGrenade_C::GrenadeThrown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TutorialGrenade_C", "GrenadeThrown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TutorialGrenade.W_TutorialGrenade_C.ExecuteUbergraph_W_TutorialGrenade
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TutorialGrenade_C::ExecuteUbergraph_W_TutorialGrenade(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TutorialGrenade_C", "ExecuteUbergraph_W_TutorialGrenade");

	Params::W_TutorialGrenade_C_ExecuteUbergraph_W_TutorialGrenade Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

