#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TutorialShieldGenerator

#include "Basic.hpp"

#include "W_TutorialContent_Base_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_TutorialShieldGenerator.W_TutorialShieldGenerator_C
// 0x0018 (0x02C0 - 0x02A8)
class UW_TutorialShieldGenerator_C final : public UW_TutorialContent_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_W_TutorialShieldGenerator_C;        // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Gold_Mined;                                        // 0x02B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         GoldToMine;                                        // 0x02B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AWPN_ShieldRegeneratorItem_C*           ShieldItem;                                        // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnShown();
	void UpdateTaskText();
	void Shield_Used(int32 amount);
	void ExecuteUbergraph_W_TutorialShieldGenerator(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_TutorialShieldGenerator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_TutorialShieldGenerator_C")
	}
	static class UW_TutorialShieldGenerator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_TutorialShieldGenerator_C>();
	}
};
DUMPER7_ASSERTS_UW_TutorialShieldGenerator_C;

}

